package smb

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"text/template"
	"time"
)

type GlobalSection struct {
	Workgroup         string
	ServerString      string
	NetbiosName       string
	ServerMinProtocol string
	ServerMaxProtocol string
}

type ShareSection struct {
	ShareName  string
	Path       string
	Comment    string
	Browseable bool
	GuestOK    bool
	ForceGroup string
	ValidUsers []string
	WriteList  []string
	ReadList   []string
	DenyAll    bool
}

type ConfigData struct {
	GeneratedAt string
	GlobalSection
	Shares []ShareSection
}

type Generator struct {
	mu             sync.Mutex
	confPath       string
	backupDir      string
	backupMaxCount int
}

func NewGenerator(confPath, backupDir string, backupMaxCount int) *Generator {
	if backupMaxCount <= 0 {
		backupMaxCount = 5
	}
	return &Generator{confPath: confPath, backupDir: backupDir, backupMaxCount: backupMaxCount}
}

func (g *Generator) Render(data ConfigData) (string, error) {
	if data.GeneratedAt == "" {
		data.GeneratedAt = time.Now().In(time.Local).Format(time.RFC3339)
	}
	sort.Slice(data.Shares, func(i, j int) bool { return data.Shares[i].ShareName < data.Shares[j].ShareName })
	var buf bytes.Buffer
	tpl, err := template.New("smb.conf").Funcs(template.FuncMap{"join": strings.Join}).Parse(smbConfTemplate)
	if err != nil {
		return "", err
	}
	if err := tpl.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}

func (g *Generator) Write(data ConfigData) error {
	g.mu.Lock()
	defer g.mu.Unlock()
	content, err := g.Render(data)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(g.confPath), 0750); err != nil {
		return err
	}
	if g.backupDir != "" {
		if err := g.backupCurrent(); err != nil {
			return err
		}
	}
	tmpPath := g.confPath + ".tmp"
	if err := os.WriteFile(tmpPath, []byte(content), 0600); err != nil {
		return err
	}
	if err := validateWithTestparm(tmpPath); err != nil {
		if removeErr := os.Remove(tmpPath); removeErr != nil {
			return fmt.Errorf("%w; failed to remove temporary config %s: %v", err, tmpPath, removeErr)
		}
		return err
	}
	return os.Rename(tmpPath, g.confPath)
}

func (g *Generator) ReadCurrent() (string, error) {
	b, err := os.ReadFile(g.confPath)
	if err != nil {
		return "", err
	}
	return string(b), nil
}

func (g *Generator) backupCurrent() error {
	if _, err := os.Stat(g.confPath); err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	if err := os.MkdirAll(g.backupDir, 0700); err != nil {
		return err
	}
	src, err := os.ReadFile(g.confPath)
	if err != nil {
		return err
	}
	backupPath := filepath.Join(g.backupDir, "smb.conf.bak."+time.Now().In(time.Local).Format("20060102150405"))
	// #nosec G703 -- backupDir is a trusted local service configuration value; filename is generated by the service.
	if err := os.WriteFile(backupPath, src, 0600); err != nil {
		return err
	}
	return g.pruneBackups()
}

func (g *Generator) pruneBackups() error {
	entries, err := os.ReadDir(g.backupDir)
	if err != nil {
		return err
	}
	var names []string
	for _, entry := range entries {
		if !entry.IsDir() && strings.HasPrefix(entry.Name(), "smb.conf.bak.") {
			names = append(names, entry.Name())
		}
	}
	sort.Strings(names)
	for len(names) > g.backupMaxCount {
		if err := os.Remove(filepath.Join(g.backupDir, names[0])); err != nil {
			return err
		}
		names = names[1:]
	}
	return nil
}

func validateWithTestparm(path string) error {
	if _, err := exec.LookPath("testparm"); err != nil {
		return nil
	}
	// #nosec G204 -- path points to the service-generated temporary smb.conf and is passed as an argv value, not through a shell.
	out, err := exec.Command("testparm", "-s", path).CombinedOutput()
	if err != nil {
		return fmt.Errorf("smb.conf validation failed: %w: %s", err, strings.TrimSpace(string(out)))
	}
	return nil
}

const smbConfTemplate = `# Generated by SMB Controller - DO NOT EDIT MANUALLY
# Last updated: {{.GeneratedAt}}

[global]
    workgroup = {{.Workgroup}}
    server string = {{.ServerString}}
{{- if .NetbiosName}}
    netbios name = {{.NetbiosName}}
{{- end}}
{{- if .ServerMinProtocol}}
    server min protocol = {{.ServerMinProtocol}}
{{- end}}
{{- if .ServerMaxProtocol}}
    server max protocol = {{.ServerMaxProtocol}}
{{- end}}
    security = user
    map to guest = bad user
    log level = 1
    max log size = 1000
    passdb backend = tdbsam

    # --- performance / concurrency tuning ---
    # TCP_NODELAY removes Nagle delay for small SMB ops; IPTOS_LOWDELAY hints routers.
    socket options = TCP_NODELAY IPTOS_LOWDELAY
    # Zero-copy reads via sendfile(2). Big win on sequential reads of large files.
    use sendfile = yes
    # Splice writes >= 16 KiB directly from socket to file, skipping userland copy.
    min receivefile size = 16384
    # Async I/O for reads/writes >= 16 KiB so one slow disk op does not block the worker.
    aio read size = 16384
    aio write size = 16384
    # Skip strict POSIX byte-range lock translation; clients still see SMB lock semantics.
    strict locking = no
    # Disable Linux kernel oplocks so Samba can hand out level2 (shared read) oplocks
    # to multiple clients — required for "many readers, occasional writer" workloads.
    kernel oplocks = no
    # SMB3 multichannel: lets a single client open several TCP connections to one share,
    # which is the main throughput improvement for modern Windows clients.
    server multi channel support = yes
{{- range .Shares}}

[{{.ShareName}}]
    path = {{.Path}}
    comment = {{.Comment}}
    browseable = {{if .Browseable}}yes{{else}}no{{end}}
    guest ok = {{if .GuestOK}}yes{{else}}no{{end}}
    read only = yes
{{- if .ForceGroup}}
    force group = {{.ForceGroup}}
{{- end}}
{{- if .ValidUsers}}
    valid users = {{join .ValidUsers " "}}
{{- else if .DenyAll}}
    valid users = __smb_controller_no_access__
{{- end}}
{{- if .WriteList}}
    write list = {{join .WriteList " "}}
{{- end}}
{{- if .ReadList}}
    read list = {{join .ReadList " "}}
{{- end}}
    create mask = 0664
    directory mask = 0775
    force create mode = 0664
    force directory mode = 2775
    # --- cross-user write semantics ---
    # Make new files/dirs inherit the parent directory's UNIX owner. Combined
    # with "force group" above, every entry under a share ends up with the
    # same owner+group, so the "I cannot edit the file created by another
    # SMB user" problem disappears regardless of who created it.
    inherit owner = unix only
    # New entries also inherit the parent's POSIX permissions, so an admin
    # can widen access on a subtree just by chmod'ing the directory.
    inherit permissions = yes
    # Allow any SMB user with write access to change DOS attributes (e.g.
    # toggling Read-only from Windows Explorer). Without this, only the
    # file owner can change them — exactly the workflow Windows users hit.
    dos filemode = yes
    # Same idea for timestamps: any user with write access can update them.
    dos filetimes = yes
    dos filetime resolution = yes
    # Preallocate file space in one syscall — avoids fragmentation on big writes.
    strict allocate = yes
    # Multi-client friendly oplocks: one exclusive writer OR many shared readers.
    oplocks = yes
    level2 oplocks = yes
    # Do not push SMB byte-range locks down to POSIX fcntl locks; better concurrency.
    posix locking = no
{{- end}}
`
